# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.34-bundle
    links:
      - mysql
    ports:
    # CONFIG - Change the 8181 here to expose Wikibase & MediaWiki on a different port
     - '${WIKI_HTTP_PORT}:80'
    volumes:
      - mediawiki-images-data:/var/www/html/images
      - quickstatements-data:/quickstatements/data
    depends_on:
    - mysql
    - elasticsearch
    restart: unless-stopped
    networks:
      default:
        aliases:
         - wikibase.svc
         # - wiki.personaldata.io
         # CONFIG - Add your real wikibase hostname here, for example wikibase-registry.wmflabs.org
    environment:
      - DB_SERVER
      - MW_ELASTIC_HOST
      - MW_ELASTIC_PORT
      # CONFIG - Change the default values below
      - MW_ADMIN_NAME
      - MW_ADMIN_PASS
      - MW_ADMIN_EMAIL
      - MW_WG_SECRET_KEY
      - DB_USER
      - DB_PASS
      - DB_NAME
      - QS_PUBLIC_SCHEME_HOST_AND_PORT
  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    ports:
    # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
      - "3306:3306" # 8282:80"
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    restart: unless-stopped
    ports:
    # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
     - "${WDQS_PORT}:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      # - WIKIBASE_xHOST=wikibase.svc
      - WIKIBASE_HOST
      - WDQS_HOST
  wdqs:
    image: wikibase/wdqs:0.3.10
    restart: unless-stopped
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST
      - WIKIBASE_SCHEME
      - WDQS_HOST
      - WDQS_PORT
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.10
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_SCHEME
     - WIKIBASE_HOST
     #- WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST
     - WDQS_PORT
  elasticsearch:
    image: wikibase/elasticsearch:5.6.14-extra
    restart: unless-stopped
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  # CONFING, in order to not load quickstatements then remove this entire section
  quickstatements:
    image: wikibase/quickstatements:latest
    ports:
     - "${QS_PORT}:80"
    depends_on:
     - wikibase
    volumes:
     - quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
#         - qs.personaldata.io
         - quickstatements.svc
    environment:
      - OAUTH_CONSUMER_KEY
      - OAUTH_CONSUMER_SECRET
      - WIKIBASE_HOST
      - WB_PROPERTY_NAMESPACE
      - WB_PROPERTY_PREFIX
      - WB_ITEM_NAMESPACE
      - WB_ITEM_PREFIX
      - QS_PUBLIC_SCHEME_HOST_AND_PORT
      - WB_PUBLIC_SCHEME_HOST_AND_PORT
      - WIKIBASE_SCHEME_AND_HOST

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
  quickstatements-data:
